### DISCUSSION TITLE
[docker] how does syslog-ng collect logs from journalctl?

### DISCUSSION THREAD

**Discussion by axi92** [syslog-ng/syslog-ng#4151] [Q&A] [answered]
Is there a way to operate syslog-ng inside a container and mount the log/socket from the host journalctl into the container to retrieve the logs from the host?

**Comment by axi92** [comment, marked as answer]
I found it here in the documentation https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.17/administration-guide/27#TOPIC-989643

That is the working docker-compose file

```
version: "3"

services:
  syslog-ng:
    image: balabit/syslog-ng:3.38.1
    hostname: ${DOCKER_HOSTNAME}
    volumes:
      - ./syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
      - /var/log:/var/log
      - /dev/log:/dev/log
      - /run/systemd/journal:/run/systemd/journal
    restart: unless-stopped
    command: "--no-caps"

```
And my syslog-ng.conf

```
@version: 3.38
@include "scl.conf"

source s_input {
  unix-dgram("/var/run/log");
  file("/var/log/syslog");
};

destination d_loki {
  syslog("10.64.191.113" transport("tcp") port(1514));
};

log {
  source(s_input);
  destination(d_loki);
};

```
